In [2]:
import torch

## Finding the min, max, mean, sum etc(Tensor aggregation)

In [3]:
# Create a tensor
x = torch.arange(0,100,10)
x

tensor([ 0, 10, 20, 30, 40, 50, 60, 70, 80, 90])

In [6]:
print(f"Minimum: {x.min()}")
print(f"Maximum: {x.max()}")
# print(f"Mean: {x.mean()}") # this will error
print(f"Mean: {x.type(torch.float32).mean()}") # won't work without float datatype
print(f"Sum: {x.sum()}")

# Find the mean - note: The torch.mean() function requires a tensor of float32 datatypes to work

Minimum: 0
Maximum: 90
Mean: 45.0
Sum: 450


You can also do the same as above with `torch` methods.

In [8]:
torch.max(x), torch.min(x),torch.mean(x.type(torch.float32)), torch.sum(x)

(tensor(90), tensor(0), tensor(45.), tensor(450))

## Positional min/max

In [9]:
# Create a tensor
tensor = torch.arange(10,100,10)
print(f"Tensor: {tensor}")

# Returns index of max and min values
print(f"Index where maximum value occurs: {tensor.argmax()}")
print(f"Index where minimum value occurs: {tensor.argmin()}")

Tensor: tensor([10, 20, 30, 40, 50, 60, 70, 80, 90])
Index where maximum value occurs: 8
Index where minimum value occurs: 0


## Change tensor datatype

If one tensor is in `torch.float64` and another is in `torch.float32`, you might run into some errors. So you can change the datatype of tensor

In [19]:
# Create a tensor and check its datatype
tensor = torch.arange(10.,100.,10.)
tensor.dtype

torch.float32

In [24]:
# Create a float16 tensor
tensor_float16 = tensor.type(torch.float16)
tensor_float16

tensor([10., 20., 30., 40., 50., 60., 70., 80., 90.], dtype=torch.float16)

In [25]:
# Create a float8 tensor
tensor_int8 = tensor.type(torch.int8)
tensor_int8

tensor([10, 20, 30, 40, 50, 60, 70, 80, 90], dtype=torch.int8)

## Reshaping, stacking, squeezing and unsqueezing tensors

* Reshaping - reshapes an input tensor to a defined shape
* View - Return a view of an input tensor of certain shape but keep the same memory as the original tensor
* Stacking - Combine multiple tensors on top of each other(vstack) or side by side(hstack)
* Squeeze - removes all `1` dimensions from a tensor
* Unsqueeze - add a `1` dimension to a target tensor
* Permute - Return a view of the input witn dimensions permuted(swapped) in a certain way

In [27]:
# Let's create a tensor
x = torch.arange(1,11)
x,x.shape

(tensor([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]), torch.Size([10]))

In [29]:
# Add an extra dimension
x_reshaped = x.reshape(1,10)
x_reshaped

tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

In [32]:
x_reshaped.shape

torch.Size([1, 10])

In [33]:
x_reshaped1 = x.reshape(2,5)
x_reshaped1

tensor([[ 1,  2,  3,  4,  5],
        [ 6,  7,  8,  9, 10]])

In [34]:
x_reshaped1.shape

torch.Size([2, 5])

In [36]:
x_reshaped2 = x.reshape(10,1)
x_reshaped2

tensor([[ 1],
        [ 2],
        [ 3],
        [ 4],
        [ 5],
        [ 6],
        [ 7],
        [ 8],
        [ 9],
        [10]])

In [37]:
x_reshaped2.shape

torch.Size([10, 1])

In [39]:
# Change the view
z = x.view(1,10)
z,z.shape

(tensor([[ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10]]), torch.Size([1, 10]))

In [41]:
# Changing z changes x(because a view of a tensor shares the same memory as the original input)
z[:,0] = 5
z,x

(tensor([[ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10]]),
 tensor([ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10]))

If we wanted to stack our new tensor on top of itself five times, we could do so with `torch.stack()`.

In [50]:
# Stack tensors on top of each other
x_stacked = torch.stack([x,x,x,x], dim=0)
x_stacked

tensor([[ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10],
        [ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10]])

How about removing all single dimensions from a tensor?

To do so you can use `torch.squeeze()` (I remember this as squeezing the tensor to only have dimensions over 1).

In [51]:
# torch.squeeze() - removes all single dimensions from a target tensor
print(f"Previous tensor: {x_reshaped}")
print(f"Previous shape: {x_reshaped.shape}")

# Remove extra dimension from x_reshaped
x_squeezed = x_reshaped.squeeze()
print(f"\nNew tensor: {x_squeezed}")
print(f"New shape: {x_squeezed.shape}")

Previous tensor: tensor([[ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10]])
Previous shape: torch.Size([1, 10])

New tensor: tensor([ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10])
New shape: torch.Size([10])


And to do the reverse of torch.squeeze() you can use torch.unsqueeze() to add a dimension value of 1 at a specific index.

In [52]:
print(f"Previous tensor: {x_squeezed}")
print(f"Previous shape: {x_squeezed.shape}")

## Add an extra dimension with unsqueeze
x_unsqueezed = x_squeezed.unsqueeze(dim=0)
print(f"\nNew tensor: {x_unsqueezed}")
print(f"New shape: {x_unsqueezed.shape}")

Previous tensor: tensor([ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10])
Previous shape: torch.Size([10])

New tensor: tensor([[ 5,  2,  3,  4,  5,  6,  7,  8,  9, 10]])
New shape: torch.Size([1, 10])


In [53]:
# torch.permute - rearranges the dimensions of a target tensor in a specified order
x_original = torch.rand(size=(224,224,3)) # [height, width, color_channels]

# permute the original tensor to rearrange the axis( or dim) order
x_permuted = x_original.permute(2, 0, 1) # shifts axis 0->1, 1->2, 2->0

print(f"Previous shape: {x_original.shape}")
print(f"New shape: {x_permuted.shape}")

Previous shape: torch.Size([224, 224, 3])
New shape: torch.Size([3, 224, 224])


**Note**: Because permuting returns a view (shares the same data as the original), the values in the permuted tensor will be the same as the original tensor and if you change the values in the view, it will change the values of the original.

In [54]:
x_original[0,0,0] = 123456
x_original[0,0,0], x_permuted[0,0,0]

(tensor(123456.), tensor(123456.))

## Indexing (Selectinf data from tensors)

Indexing with PyTorch is similar to indexing with NumPy.

In [56]:
# Creating a tensor
x = torch.arange(1,10).reshape(1,3,3)
x, x.shape

(tensor([[[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]]),
 torch.Size([1, 3, 3]))

In [57]:
# Let's index on our new tensor
x[0]

tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]])

In [58]:
# Let's index on the middle bracket (dim = 1)
x[0][0]

tensor([1, 2, 3])

In [59]:
# Let's index on the most inner bracket (Last dimension)
x[0][0][0]

tensor(1)

In [71]:
x[0][0][1]

tensor(2)

In [72]:
x[0][1][1]

tensor(5)

In [61]:
x[0][0][2]

tensor(3)

In [63]:
x[0][1][0]

tensor(4)

In [64]:
x[0][2][0]

tensor(7)

In [65]:
x[0][2][2]

tensor(9)

In [66]:
# You can also use ":" to select "all" of a target dimension
x[:,0]

tensor([[1, 2, 3]])

In [67]:
x[:,1]

tensor([[4, 5, 6]])

In [68]:
# Get all values of 0th and 1st dimensions but only index 1 of 2nd dimension
x[:,:,1]

tensor([[2, 5, 8]])

In [70]:
# Get all values of the o dimension but only the 1 index of 1st and 2nd dimension
x[:,1,1] #same as x[0][1][1]

tensor([5])

In [73]:
# Get index 0 of 0th and 1st dimension and all values of 2nd dimension
x[0,0,:]

tensor([1, 2, 3])

In [74]:
# Index on x to return 9
print(x[0][2][2])

# Index on x to return 3,6,9
print(x[:,:,2])

tensor(9)
tensor([[3, 6, 9]])


## PyTorch tensors and NumPy

The two main methods you'll want to use for NumPy to PyTorch (and back again) are:

   * `torch.from_numpy(ndarray)` - NumPy array -> PyTorch tensor.
   * `torch.Tensor.numpy()` - PyTorch tensor -> NumPy array.

In [75]:
# NumPy array to tensor
import torch
import numpy as np
array = np.arange(1.0, 8.0)
tensor = torch.from_numpy(array)
array, tensor

(array([1., 2., 3., 4., 5., 6., 7.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [76]:
# Change the array, keep the tensor
array = array + 1
array, tensor

(array([2., 3., 4., 5., 6., 7., 8.]),
 tensor([1., 2., 3., 4., 5., 6., 7.], dtype=torch.float64))

In [77]:
# Tensor to NumPy array
tensor = torch.ones(7) # create a tensor of ones with dtype=float32
numpy_tensor = tensor.numpy() # will be dtype=float32 unless changed
tensor, numpy_tensor

(tensor([1., 1., 1., 1., 1., 1., 1.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

In [79]:
# Change the tensor, keep the array the same
tensor = tensor + 1
tensor, numpy_tensor

(tensor([2., 2., 2., 2., 2., 2., 2.]),
 array([1., 1., 1., 1., 1., 1., 1.], dtype=float32))

## Reproducibility (trying to take the random out of random)

In [80]:
import torch

# Create two random tensors
random_tensor_A = torch.rand(3, 4)
random_tensor_B = torch.rand(3, 4)

print(f"Tensor A:\n{random_tensor_A}\n")
print(f"Tensor B:\n{random_tensor_B}\n")
print(f"Does Tensor A equal Tensor B? (anywhere)")
random_tensor_A == random_tensor_B

Tensor A:
tensor([[0.2540, 0.0026, 0.3738, 0.4830],
        [0.9059, 0.6315, 0.2724, 0.2264],
        [0.8138, 0.8769, 0.7012, 0.6826]])

Tensor B:
tensor([[0.8069, 0.6344, 0.4269, 0.0292],
        [0.5764, 0.9125, 0.4488, 0.0792],
        [0.1016, 0.0412, 0.4355, 0.3016]])

Does Tensor A equal Tensor B? (anywhere)


tensor([[False, False, False, False],
        [False, False, False, False],
        [False, False, False, False]])

In [81]:
import torch
import random

# # Set the random seed
RANDOM_SEED=42 # try changing this to different values and see what happens to the numbers below
torch.manual_seed(seed=RANDOM_SEED) 
random_tensor_C = torch.rand(3, 4)

# Have to reset the seed every time a new rand() is called 
# Without this, tensor_D would be different to tensor_C 
torch.random.manual_seed(seed=RANDOM_SEED) # try commenting this line out and seeing what happens
random_tensor_D = torch.rand(3, 4)

print(f"Tensor C:\n{random_tensor_C}\n")
print(f"Tensor D:\n{random_tensor_D}\n")
print(f"Does Tensor C equal Tensor D? (anywhere)")
random_tensor_C == random_tensor_D

Tensor C:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Tensor D:
tensor([[0.8823, 0.9150, 0.3829, 0.9593],
        [0.3904, 0.6009, 0.2566, 0.7936],
        [0.9408, 0.1332, 0.9346, 0.5936]])

Does Tensor C equal Tensor D? (anywhere)


tensor([[True, True, True, True],
        [True, True, True, True],
        [True, True, True, True]])

## Running tensors on GPUs (and making faster computations)

### Getting PyTorch to run on the GPU

In [82]:
# Check for GPU
import torch
torch.cuda.is_available()

False

In [83]:
# Set device type
device = "cuda" if torch.cuda.is_available() else "cpu"
device

'cpu'