# Resource :- https://www.learnpytorch.io/

In [2]:
import torch
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt

In [3]:
print(torch.__version__)


1.12.1


# Introduction to Tensors
## Creating tensors
### PyTorch tensors are created using torch.Tensor() = https://www.learnpytorch.io/00_pytorch_fundamentals/

In [4]:
# Scalar
scalar = torch.tensor(7)
scalar

tensor(7)

In [5]:
scalar.ndim

0

In [6]:
# Get tensor back as Python int (only works with one-element tensors)
scalar.item()

7

In [7]:
# vector
vector = torch.tensor([4,5])
vector

tensor([4, 5])

In [8]:
# Check the number of dimensions of vector
vector.ndim

1

In [9]:
# Check shape of vector
vector.shape

torch.Size([2])


The above returns torch.Size([2]) which means our vector has a shape of [2]. This is because of the two elements we placed inside the square brackets ([4, 5]).

In [10]:
# Matrix
MATRIX = torch.tensor([[3,4],
                      [5,6]])
MATRIX

tensor([[3, 4],
        [5, 6]])

In [11]:
# Check number of dimensions
MATRIX.ndim

2

In [12]:
MATRIX.shape

torch.Size([2, 2])

In [18]:
MATRIX[0]

tensor([3, 4])

We get the output torch.Size([2, 2]) because MATRIX is two elements deep and two elements wide.

In [13]:
# Tensor
TENSOR = torch.tensor([[[1, 2, 3],
                        [3, 6, 9],
                        [2, 4, 5]]])
TENSOR

tensor([[[1, 2, 3],
         [3, 6, 9],
         [2, 4, 5]]])

In [14]:
# Check number of dimensions for TENSOR
TENSOR.ndim

3

In [17]:
# Check shape of TENSOR
TENSOR.shape   #[colour_channels, height, width]

torch.Size([1, 3, 3])

In [19]:
TENSOR[0]

tensor([[1, 2, 3],
        [3, 6, 9],
        [2, 4, 5]])

# Random tensors

Why random tensors?

Random tensors are important because the way many neural networks learn is that they start with ramdom nembers and then adjust those random numbers to better represent the data.

`Start with random numbers -> look at data -> update random numbers -> look at data -> update random numbers`

Torch random tensor - https://pytorch.org/docs/stable/generated/torch.rand.html 

In [22]:
# Create a random tensor of size (4,5)
random_tensor = torch.rand(4,5)

In [23]:
random_tensor

tensor([[0.0460, 0.7026, 0.0444, 0.2409, 0.4913],
        [0.6227, 0.7156, 0.4633, 0.6371, 0.8128],
        [0.2922, 0.0807, 0.4087, 0.9140, 0.5270],
        [0.9968, 0.0673, 0.9320, 0.7994, 0.2546]])

In [24]:
random_tensor.ndim

2

In [25]:
random_tensor = torch.rand(1,4,5)
random_tensor

tensor([[[0.1177, 0.2444, 0.2738, 0.8665, 0.5619],
         [0.1433, 0.1134, 0.7443, 0.5468, 0.8427],
         [0.9055, 0.2923, 0.8419, 0.3440, 0.6878],
         [0.8553, 0.3258, 0.3276, 0.0586, 0.6404]]])

In [26]:
random_tensor.ndim

3

In [28]:
# Create a random tensor with similar shape to an image tensor
random_image_size_tensor = torch.rand(size=(3,224,224)) # Colour channel,height,width
random_image_size_tensor.shape, random_image_size_tensor.ndim

(torch.Size([3, 224, 224]), 3)

## Zeros and ones

In [31]:
# Creating a tensor of all zeros
zeros = torch.zeros(size=(4,5))
zeros

tensor([[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]])

In [32]:
zeros* random_tensor

tensor([[[0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.],
         [0., 0., 0., 0., 0.]]])

In [33]:
# Create a tensor of all ones
ones = torch.ones(size=(4,5))
ones

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]])

In [34]:
ones.dtype

torch.float32

In [35]:
random_tensor.dtype

torch.float32

In [36]:
## Creating a range of tensors and tensors-like

In [40]:
# Use torch.range()
one_to_ten = torch.arange(start=0,end=11,step=1) #torch.arange(1,11) 
one_to_ten

tensor([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [42]:
# Creating tensors like (Returns a tensor filled with the scalar value 0, with the same size as in one_to_ten)
ten_zeros = torch.zeros_like(input=one_to_ten)
ten_zeros

tensor([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

## Tensor datatypes

Resource :- https://pytorch.org/docs/stable/tensors.html

**Note** :- Tensor datatypes is one of the 3 big errors you'll run into with PyTorch and deep learning:
   1. Tensors not right datatype
   2. Tensors not right shape
   3. Tensors not on the right device

In [45]:
# Float 32 tensor
float_32_tensor = torch.tensor([1.0,3.4,5.6], dtype=None)
float_32_tensor


tensor([1.0000, 3.4000, 5.6000])

In [47]:
float_32_tensor.dtype # If dtype is given none then also the default type is float32

torch.float32

In [48]:
# Float 16 tensor
float_16_tensor = torch.tensor([1.0,3.4,5.6], dtype=torch.float16)
float_16_tensor.dtype

torch.float16

Single precision is 32-bit and half precision is 16-bit, but if we require more precise value then we have to go with 32-bit otherwise in term of memory space it is better to go with 16bit

In [49]:
float_32_tensor = torch.tensor([3.0,6.0,9.0],
                              dtype=None, #What datatype is the tensor (e.g. float32 or float16)
                              device=None, #What device is your tensor on like GPU or CPU
                              requires_grad = False) # Whether or not to track gradients with this operations
float_32_tensor

tensor([3., 6., 9.])

In [50]:
float_32_tensor.dtype

torch.float32

In [51]:
float_16_tensor = float_32_tensor.type(torch.float16)
float_16_tensor

tensor([3., 6., 9.], dtype=torch.float16)

In [52]:
float_16_tensor * float_32_tensor

tensor([ 9., 36., 81.])

In [53]:
int_32_tensor = torch.tensor([3,4,5], dtype=torch.int32)
int_32_tensor

tensor([3, 4, 5], dtype=torch.int32)

In [54]:
float_32_tensor * int_32_tensor # It may produce error when we perform multiplication of two different datatype

tensor([ 9., 24., 45.])

## Getting information from tensors

1. To get datatype from a tensor, we can use `tensor.dtype`
2. To get shape frem a tensor, we can use `tensor.shape`
3. To get device from a tensor, we can use `tensor.device`

In [55]:
# Create a tensor
some_tensor = torch.rand(3,4)
some_tensor

tensor([[0.0555, 0.5322, 0.7520, 0.6200],
        [0.1217, 0.0452, 0.3642, 0.6470],
        [0.8329, 0.0969, 0.9102, 0.9131]])

In [59]:
# Find out details about some tensor
print(some_tensor)
print(f"Datatype of tensor: {some_tensor.dtype}")
print(f"Shape of tensor: {some_tensor.shape}")  # Attribute
print(f"Shape of tensor: {some_tensor.size()}") # Function
print(f"Device tensor is on: {some_tensor.device}") # By default it is in CPU

tensor([[0.0555, 0.5322, 0.7520, 0.6200],
        [0.1217, 0.0452, 0.3642, 0.6470],
        [0.8329, 0.0969, 0.9102, 0.9131]])
Datatype of tensor: torch.float32
Shape of tensor: torch.Size([3, 4])
Shape of tensor: torch.Size([3, 4])
Device tensor is on: cpu


## Manipulating Tensors (Tensor operations)

Tensor operations include:
1. Addition
2. Subtraction
3. Multiplication (element-wise)
4. Division
5. Matrix multiplication

In [60]:
# Create a tensor and add 10 to it
tensor = torch.tensor([5,6,7])
tensor + 10

tensor([15, 16, 17])

In [61]:
# Multiply tensor by 10
tensor * 10

tensor([50, 60, 70])

In [62]:
tensor

tensor([5, 6, 7])

In [63]:
# Subtract 10
tensor - 10

tensor([-5, -4, -3])

In [64]:
# Try out PyTorch in-built functions
torch.mul(tensor, 10)

tensor([50, 60, 70])

In [65]:
torch.add(tensor,10)

tensor([15, 16, 17])

### Matrix multiplication

Two main ways of performing multiplication in neural networks and deep learning:
1. Element-wise multiplication
2. Matrix multiplication(dot product)

In [67]:
# Element wise multiplication
print(tensor, "*", tensor)
print(f"Equals: {tensor * tensor}")

tensor([5, 6, 7]) * tensor([5, 6, 7])
Equals: tensor([25, 36, 49])


In [68]:
# Matrix multiplication
torch.matmul(tensor,tensor)

tensor(110)

In [69]:
tensor

tensor([5, 6, 7])

In [70]:
%%time
value = 0
for i in range(len(tensor)): # Matrix multiplication using loop
    value += tensor[i] * tensor[i]
print(value)

tensor(110)
CPU times: total: 0 ns
Wall time: 6 ms


In [71]:
%%time
torch.matmul(tensor, tensor) # faster

CPU times: total: 0 ns
Wall time: 0 ns


tensor(110)